### ISSUE TITLE
Journal Links bug - handleSceneClicked

### ISSUE THREAD

**Issue by shemetz** [jegasus/scene-clicker#12]
the handleSceneClicked code, at least in V10 if not also earlier, throws an error when trying to click on any journal link (including macros for example):

```
libWrapper-wrapper.js:669 Uncaught TypeError: Cannot read properties of undefined (reading 'documentName')
[Detected 2 packages: scene-clicker, lib-wrapper]
    at handleSceneClicked (scene-clicker.js:8:18)
    at HTMLAnchorElement.new_onClickContentLink (scene-clicker.js:136:8)
```

**Comment by shemetz** [comment]
The error in the code is around here:

```
function handleSceneClicked(event, document)
{
    if (document.documentName != "Scene") {
        return false;
    }
```

When clicking a macro journal link, the document is undefined, and the document name can be found in `event.currentTarget.dataset.type`.
